# Generated by Django 5.0.6 on 2024-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreto', models.CharField(max_length=100)),
                ('ano_ejecucion', models.IntegerField(max_length=10)),
                ('mes_pago', models.CharField(max_length=100)),
                ('ano_programa', models.IntegerField(max_length=10)),
                ('tipo_programa', models.CharField(max_length=100)),
                ('alternativa', models.CharField(max_length=250)),
                ('tipo_proyecto', models.CharField(max_length=250)),
                ('incremento', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('codigo_rut_proyecto_grupo_beneficiario', models.CharField(max_length=100)),
                ('nombre_proyecto_beneficiario', models.CharField(max_length=250)),
                ('sistema_utilizado', models.CharField(max_length=250)),
                ('resolucion_asignacion_subsidios', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('unidad', models.CharField(max_length=100)),
                ('uf', models.IntegerField(max_length=25)),
                ('valor_uf_utilizado', models.IntegerField(max_length=25)),
                ('valor', models.IntegerField(max_length=25)),
                ('valor_miles', models.IntegerField(max_length=100)),
                ('observacion', models.CharField(max_length=500)),
                ('num_resolucion_pago', models.IntegerField(max_length=100)),
                ('fecha_resolucion_pago', models.DateField()),
                ('num_ap_rpm', models.CharField(max_length=100)),
                ('fecha_ap_rpm', models.DateField()),
                ('rut_beneficiario', models.CharField(max_length=100)),
                ('dv', models.CharField(max_length=100)),
                ('num_giro', models.IntegerField(max_length=100)),
                ('porcentaje_avance_cuota', models.IntegerField(max_length=100)),
                ('ahorro', models.IntegerField(max_length=100)),
                ('nombre_constructora_vendedor', models.CharField(max_length=250)),
                ('rut_constructora_vendedor', models.CharField(max_length=300)),
                ('dv_constructora_vendedor', models.CharField(max_length=300)),
                ('nombre_mandante', models.CharField(max_length=250)),
                ('rut_mandante', models.CharField(max_length=100)),
                ('dv_mandante', models.CharField(max_length=100)),
                ('ejecucion_pago', models.CharField(max_length=100)),
                ('num_ingreso_ofpa', models.IntegerField(max_length=100)),
                ('fecha_ingreso_ppeps', models.DateField()),
                ('caja_semana', models.CharField(max_length=100)),
            ],
        ),
    ]
