# Generated by Django 5.0.6 on 2024-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviuApp', '0002_alter_subsidio_ahorro_alter_subsidio_ano_ejecucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidio',
            name='tipo_programa',
            field=models.CharField(max_length=250),
        ),
    ]
